server:
  port: 8081
#spring:
#  profiles:
##    active: prod
#    active: dev
#
---

server:
  port: 8083
spring:
  profiles: dev

---

server:
  port: 8084
spring:
  profiles: prod
#
#---
#
#
#
#
#
#
#
##person:
##  lastName: zhangsan
##  age: 18
##  boss: false
##  birth: 1988/11/11
##  maps: {k1: v1,k2: 12,k3: test}
##  lists:
##    - number1
##    - number2
##  dog:
##    petName: 佩奇
##    petAge: 2